spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/database1
    username: vegetarianez
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
