services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: vegetarianez
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: database1


volumes:
  postgres_data: